### ISSUE TITLE
Heartbeat posílat nezávisle na GPS PPS signálu

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TFPM01#6]
Aktuálně se Heartbeat paket posílá pouze v případě, že je přítomný PPS signál. V případě, že senzor z nějakého důvodu nefunguje, tak tohle by byla věc, která by se ověřovala jako první. Jestli je problém ve spojení mezi MCU a FMU nebo jestli je problém se čtením ze senzoru. 

Heartbeat paket nemusí být vůbec synchronní k PPS signálu.

**Comment by kaklik** [comment]
Tohle zřejmě přestlalo být relevantní implementací driveru prachového senzoru přímo do PX4.
